### ISSUE TITLE
Content Elemente aus Artikeln hier rein kopieren geht leider nicht

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_translatedcontentarticle#10]
Content Elemente aus Artikeln hier rein kopieren geht leider nicht

**Comment by MacKP** [comment]
Genauere Beschreibung: Es geht nicht, wenn man Elemente aus Contao Artikeln in MM rein kopieren möchte, da dann die Verknüpfung zu MM nicht gesetzt wird (der Kontext wird nicht gesetzt).

**Comment by MacKP** [comment]
Ist auch in 2.1.2 noch nicht möglich. Nach dem Einfügen werden die eingefügten Elemente nicht angezeigt.

**Comment by zonky2** [comment]
@MacKP getestet mit 2.1.2: geht bei mir - ggf. noch nicht aktuelle Version?

**Comment by MacKP** [comment]
Ich hatte sogar den vendor komplett gelöscht und hab alles so eingetragen wie in deiner Anleitung steht. Von daher kann ich mir nicht erklären, warum es bei dir geht aber bei mir nicht. Vllt gucken wir nachher mal kurz zusammen

**Comment by zonky2** [comment]
solange bei Dir ein Ordner "driver" vorhanden ist, bist Du auf dem Holzweg - ggf. in der composer.lock mal gucken, was installiert wurde

**Comment by zonky2** [comment]
wenn du das require nicht einträgst, kommt die Quelle sicher von gitlab und nicht von github :D

**Comment by MacKP** [comment]
Wichtig ist die Reihenfolge in repositories: das attribute muss vor packagist stehen !
