### ISSUE TITLE
Clipboard-Icon in Contao wird nicht zurück gesetzt nach einfügen in MM

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_translatedcontentarticle#17]
Clipboard-Icon in Contao wird nicht zurück gesetzt nach einfügen in MM

siehe https://github.com/MetaModels/attribute_contentarticle/issues/12

**Comment by MacKP** [comment]
Kann nicht nachvollzogen werden. Bitte schließen :stuck_out_tongue:
