### ISSUE TITLE
Info Button von einem CE wirft einen Internal Server Error

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_translatedcontentarticle#20]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_translatedcontentarticle/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.4     |                                  |
| Contao version:                     |     4.9     |                                  |
| MetaModels version:                 |     2.2dev     |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description

Ich habe schon bestehende Content Elemente in dem Attribut und klicke auf den Info Button. Die Info geht auf und im Inhalt bekomme ich folgenden Fehler:
`An exception occurred while executing 'SELECT `theme_alias` AS value FROM mm_theme WHERE id='' LIMIT 0,1': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'usr_p381880_3.mm_theme' doesn't exist`

**Comment by zonky2** [comment]
works fine for me
![FireShot Pro Webpage Screenshot #852 - 'I mm220 dev metamodel me' - mm](https://user-images.githubusercontent.com/1045318/152683034-330bec08-9b1d-46c3-b06b-2a3faaa7954f.jpg)

@MacKP pls check

**Comment by MacKP** [comment]
Bei mir ist immer noch der selbe Fehler vorhanden. Update von gestern mit den aktuellen Versionen von allen MM-Modulen.
