### ISSUE TITLE
Bezogene Inhaltselemente können nicht ausgewählt werden

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_translatedcontentarticle#21]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_translatedcontentarticle/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.4     |                                  |
| Contao version:                     |     4.9     |                                  |
| MetaModels version:                 |     2.2dev     |                                  |
| Installation via composer:          | yes |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |          |                                  |

## Issue description

Ich würde gerne ein Inhaltselement von einer anderen Stelle nutzen. Kann das aber nicht auswählen, da der Button für die Auswahl auf disabled gesetzt ist.
Bezogene Artikel geht im gegensatz dazu ohne Probleme.

**Comment by zonky2** [comment]
Wenn Du Typ Inhaltselement ausgewählt hast, musst Du erst auf den Stift vom Atrikel klicken... dann CE auswählen

![FireShot Pro Webpage Screenshot #855 - 'I mm220 dev metamodel me' - mm](https://user-images.githubusercontent.com/1045318/152852969-b2e5ac00-74d6-4562-81a3-7a4cb8d35807.jpg)

**Comment by MacKP** [comment]
Das Problem besteht bei mir in der aktuellen Version auch nicht mehr.
