### ISSUE TITLE
Exception when trying to Edit the Content Elements

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_translatedcontentarticle#5]
When I install attribute_translatedcontentarticle I can't Edit attribute_contentarticle. When I click 'Edit' in the inputmask I get:
```
An exception occurred while executing 'SELECT 1 FROM `$ptable` WHERE id='1' LIMIT 0,1':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.$ptable' doesn't exist
```
Kind regards

**Comment by zonky2** [comment]
@MacKP getestet mit 2.1.2: tritt bei mir nicht (mehr) auf
