### ISSUE TITLE
Column 'ptable' cannot be null

### ISSUE THREAD

**Issue by k-webdesign** [MetaModels/attribute_translatedcontentarticle#7]
Hi,
beim Anlegen des ersten Content Elements habe ich andere Schaltflächen. Wähle ich "Speichern und neu" des ersten Content-Elements in "Edit" kommt ständig der Fehler:

Was ist das Problem?
```An exception occurred while executing 'INSERT INTO tl_content (`metamodel_filtering`, `metamodel_rendersettings`, `metamodel_fef_autosubmit`, `metamodel_fef_template`, `pid`, `sorting`, `ptable`, `tstamp`) VALUES ('0', '0', '1', 'mm_filter_default', 6, 48, NULL, 0)': SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ptable' cannot be null```

**Comment by zonky2** [comment]
hier sollte es doch so sein wie bei https://github.com/MetaModels/attribute_contentarticle, dass die Auswahl/Modalfenster erst nach dem ersten Speichern enabled wird und vorher disabled ist

**Comment by zonky2** [comment]
@MacKP @k-webdesign getestet mit 2.1.2: tritt bei mir nicht (mehr) auf
